# NUMPY

#### Numpy is the most important library in the Python. NumPy is a powerful Python library for numerical computing. It provides support for large, multi-dimensional arrays and matrices, along with mathematical functions to operate on these arrays efficiently. 

# Creating NumPy Arrays
NumPy provides various methods to create arrays:

In [ ]:
import numpy as np
print(np.zeros((3,3)))   # 3x3 array of zeros
print(np.ones((2,4)))    # 2x4 array of ones
print(np.arange(1,10,3)) 
print(np.eye(7))          # 7x7 array of identity
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])
print(np.dot(A,B))       # Matrix multiplication # 3x3 identity matrix
print(np.full((3,3),9))   # Creates an array filled with a specific value
print(np.linspace(0,10,6))  # Generates evenly spaced numbers between start and stop[np.linspace(start,stop,num)]
print(np.arange(0,10,1))   # Creates an array with a range of values[np.arange(start,stop,step)]

In [ ]:
import numpy as np

print(np.zeros((3, 3)))  # 3x3 array of zeros

print(np.ones((2, 4)))   # 2x4 array of ones

print(np.eye(3))         #3x3 array of identity

A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
print(np.dot(A, B))  # Matrix multiplication# 3x3 identity matrix

print(np.full((3,3), 9)) #Creates an array filled with a specific value

print(np.linspace(0, 10, 6)) #Generates evenly spaced numbers between start and stop [np.linspace(start, stop, num)]

print(np.arange(0, 10, 1))   #Creates an array with a range of values [np.arange(start, stop, step)]

print(np.random.rand(3,4))    #Generates a random array (uniform distribution)

print(np.random.randn(3,3))    #Generates a random array (normal distribution)

print(np.random.randint(1, 10, (3,3)))  #Generates random integers in a given range

## Important Array Methods
NumPy provides several useful functions to analyze arrays:

In [ ]:
# Functions
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15])  #Creates a NumPy array from the list of numbers 1 to 15.
a=np.split(arr,[0,2,3])  #Splits the array into multiple sub-arrays at the specified indices.
print(a)
print(arr.sum())  # Returns the sum of all elements in the array. Use: Total value or aggregation of numbers.
print(arr.max())  # Returns the maximum value (largest element) in the array. Use: To find the highest number in data.
print(arr.min())  # Returns the minimum value (smallest element) in the array. Use: To find the lowest number in data.
print(arr.argmax())  # Returns the index of the maximum value in the array. Use: To know the position of the highest value.
print(arr.argmin())  # Returns the index of the minimum value in the array. Use: To know the position of the lowest value.
print(np.var(arr))   # Calculates the variance, i.e., how much the numbers vary from the mean. Use: Measures spread or dispersion of data.
print(np.std(arr))   # Calculates the standard deviation, which is the square root of variance. Use: Indicates how tightly the data is clustered around the mean.
print(np.median(arr))  # Returns the middle value of the array when sorted. Use: A good measure of central tendency, especially for skewed data.
print(arr.mean())   # Returns the average (mean) of all the values in the array. Use: Common measure of central value in data.

In [ ]:
import numpy as np
arr = np.array([[1,2,3],[5,6,7]])
print(arr.shape)      #Returns the shape of an array

print(arr.reshape(3,2))  #Reshapes an array

print(arr.ravel())   #Flattens a multi-dimensional array

print(arr.T)   #Transposes an array (swaps rows & columns)

print(np.expand_dims(arr, axis=0))  #Adds an extra dimension

print(np.squeeze(arr))   #Removes single-dimensional entries

## Difference Between Lists and NumPy Arrays
NumPy arrays support element-wise operations, whereas lists behave differently.

In [10]:
# List vs NumPy array operations
import numpy as np
list1 = [1, 2, 3, 4]
array1 = np.array([1, 2, 3, 4])

print('List addition:', list1 + list1)  # Concatenation
print('NumPy array addition:', array1 + array1)  # Element-wise addition

print('List multiplication:', list1 * 2)  # Repeats list
print('NumPy array multiplication:', array1 * 2)  # Element-wise multiplication

List addition: [1, 2, 3, 4, 1, 2, 3, 4]
NumPy array addition: [2 4 6 8]
List multiplication: [1, 2, 3, 4, 1, 2, 3, 4]
NumPy array multiplication: [2 4 6 8]


## Broadcasting in NumPy
Broadcasting allows NumPy to perform operations on arrays of different shapes.

In [13]:
# Broadcasting example
A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([1, 2, 3])  # Shape (3,)
C = A + B  # Broadcasting
print(C)

[[2 4 6]
 [5 7 9]]


## Row-Major and Column-Major Storage
NumPy stores arrays in row-major order by default, but you can change it to column-major using order='F'.

In [16]:
# Row-major vs Column-major
arr = np.array([[1, 2], [3, 4]], order='C')
print('Row-major:', arr.flatten(order='C'))
print('Column-major:', arr.flatten(order='F'))

Row-major: [1 2 3 4]
Column-major: [1 3 2 4]


## Array Attributes
Some important attributes of NumPy arrays include:

In [19]:
# Array attributes
arr = np.array([[1, 2, 3], [4, 5, 6]])
print('Shape:', arr.shape)
print('Number of dimensions:', arr.ndim)

Shape: (2, 3)
Number of dimensions: 2


## Concept of Axis in NumPy
Axis 0 refers to rows (vertical operations), while Axis 1 refers to columns (horizontal operations).

In [22]:
# Axis example
arr = np.array([[1, 2], [3, 4]])
print('Sum along axis 0:', arr.sum(axis=0))  # Column-wise sum
print('Sum along axis 1:', arr.sum(axis=1))  # Row-wise sum

Sum along axis 0: [4 6]
Sum along axis 1: [3 7]


## Reshaping Arrays
We can reshape arrays into different dimensions.

In [25]:
# Reshaping example
arr = np.arange(6).reshape(2, 3)
print(arr)

[[0 1 2]
 [3 4 5]]


## Splitting Arrays
NumPy provides functions to split arrays into multiple parts.

In [32]:
# Splitting an array
arr = np.array([1, 2, 3, 4, 5, 6])
split_arr = np.split(arr, 3)
print(split_arr)

[array([1, 2]), array([3, 4]), array([5, 6])]


## hsplit vs vsplit
hsplit() splits along columns (horizontally)
vsplit() splits along rows (vertically)

In [36]:
# hsplit vs vsplit
arr = np.arange(16).reshape(4, 4)
print('Horizontal Split:', np.hsplit(arr, 2))
print('Vertical Split:', np.vsplit(arr, 2))

Horizontal Split: [array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])]
Vertical Split: [array([[0, 1, 2, 3],
       [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])]


## Stacking Arrays
NumPy allows stacking arrays vertically and horizontally.

In [39]:
# Stacking arrays
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print('Horizontal Stack:', np.hstack((a, b)))
print('Vertical Stack:', np.vstack((a, b)))

Horizontal Stack: [1 2 3 4 5 6]
Vertical Stack: [[1 2 3]
 [4 5 6]]


In [3]:
import numpy as np
a = np.array([5],ndmin=10)
print(a)

[[[[[[[[[[5]]]]]]]]]]


In [5]:
###1. How do you create a NumPy array from a Python list and specify the data type?
import numpy as np
list = [1,2,3,4,5]
arr = np.array(list,dtype = float)
print(arr)

[1. 2. 3. 4. 5.]


In [7]:
###2.How do you generate an array of evenly spaced numbers?
import numpy as np
print(np.linspace(0,10,6)) #(start,stop,num)
print(np.arange(0,10,2))   #(start,stop,step)

[ 0.  2.  4.  6.  8. 10.]
[0 2 4 6 8]


In [9]:
###3. Using np.arange(start, stop, step)
import numpy as np
print(np.arange(0,10,2))

[0 2 4 6 8]


In [11]:
###4. Using np.linspace(start, stop, num)
import numpy as np
print(np.linspace(0,10,2))

[ 0. 10.]


In [13]:
###5. How to reshape a NumPy array?
import numpy as np
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr.reshape(1,9))
print(arr.reshape(3,3))

[[1 2 3 4 5 6 7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [15]:
#6. How do you flatten a multi-dimensional NumPy array?
import numpy as np
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr.flatten())
print(arr.ravel())

[1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


In [17]:
#7. How to generate a NumPy array of random numbers?
import numpy as np
print(np.random.rand(2,2))  # 2x2 matrix with random numbers between 0 and 1
np.random.randint(1, 10, (2, 2)) # 2x2 matrix with random integers from 1 to 9

[[0.82589366 0.48402794]
 [0.4176692  0.07883327]]


array([[9, 6],
       [3, 3]])

In [19]:
# 8. How to compute the mean, median, and standard deviation of an array?
import numpy as np

In [21]:
#1. Find indices of non zeros elements from [1,2,0,0,4,0]
import numpy as np
arr = np.array([1,2,0,0,4,0])
a = np.nonzero(arr)
print(a[0])

[0 1 4]


In [23]:
#2. Create a null vector of size 10
import numpy as np
null_vector = np.zeros(10)
print(null_vector)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [25]:
#3. Create a null vector of size 10 but the 5th value is one
import numpy as np
null_vector = np.zeros(10)
null_vector[4] = 1
print(null_vector)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [27]:
#4. Reverse a vector (first element becomes last)
import numpy as np
vector = [1,2,0,0,4,0]
rev = vector[::-1]
print(rev)  

[0, 4, 0, 0, 2, 1]


In [29]:
#5. Create a 3x3 matrix with values ranging from 0 to 8
#matrix = [[0,1,2],[3,4,5],[6,7,8]]
#for row in matrix:
#    print(row)

#OR
#Using range() and reshape()
import numpy as np
matrix = np.reshape(range(9),(3,3))
print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [31]:
#6. Create a 3x3 identity matrix
import numpy as np
print(np.eye(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [33]:
#7. Create a 10x10 array with random values and find the maxmimum and minimum values
import numpy as np
arr = np.random.randint(0,10,(10,10))
print(arr)
print(np.max(arr))
print(np.min(arr))

[[5 1 4 8 4 4 6 7 2 5]
 [8 3 7 0 7 8 3 8 4 2]
 [7 0 9 8 8 2 1 3 8 8]
 [0 7 3 3 2 3 8 6 9 3]
 [9 8 4 5 3 1 1 4 4 2]
 [1 8 7 9 3 2 2 7 9 0]
 [0 1 4 5 7 6 7 8 2 7]
 [0 8 4 8 5 8 8 5 1 6]
 [2 3 3 1 6 3 0 0 4 9]
 [6 0 1 6 8 5 3 1 6 0]]
9
0


In [35]:
#8.Create a random vector of size 30 and find the mean value
import numpy as np
vector = np.random.random(30)
mean_value = np.mean(vector)
print(vector)
print(mean_value)

[0.97702661 0.42249707 0.31585722 0.81144423 0.14527492 0.82775776
 0.76139852 0.14781556 0.91996696 0.12197857 0.14927893 0.095019
 0.76009058 0.01113224 0.85919698 0.73648729 0.69415619 0.8047101
 0.92191877 0.05948469 0.53244536 0.32178456 0.87249349 0.63031073
 0.79874047 0.43066117 0.95076143 0.88989015 0.29838027 0.4806676 ]
0.5582875807850333


In [37]:
#9. Create a 2d array with 1 on the border and 0 inside
import numpy as np
# Create 2D array with 1s on the border and 0s inside
array = np.ones((5, 5))#Is line mein ek 5x5 ka array banaya gaya hai jisme saare elements 1 honge. Matlab array ka har element initial value 1 hoga
array[1:-1, 1:-1] = 0 #Yeh line kaafi important hai. Iska matlab hai, jo inner part of the array hai (jo borders ke andar hai), usko 0 set kar do. Matlab, 1 ke border ke andar jo bhi values hain, unko 0 bana diya gaya hai.
print(array)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [39]:
import numpy as np
arr = np.array([[1,2,3],[4,5,6]])
print(arr)
print(arr.shape)
print(arr.T)
print(arr.reshape(1,6))
print(arr.reshape(2,3))

[[1 2 3]
 [4 5 6]]
(2, 3)
[[1 4]
 [2 5]
 [3 6]]
[[1 2 3 4 5 6]]
[[1 2 3]
 [4 5 6]]


In [99]:
#########################Advanced Questions###################################
### 1 . Array Manipulation
### 🔹 Generate a 5×5 matrix where elements on the border are 1, and the inside is 0.
# Expected Output:
# [[1. 1. 1. 1. 1.]
#  [1. 0. 0. 0. 1.]
#  [1. 0. 0. 0. 1.]
#  [1. 0. 0. 0. 1.]
#  [1. 1. 1. 1. 1.]]
# 🔹 Reshape a 1D array of 20 elements into a 4×5 matrix without using reshape().
#🔹 Rotate a given 4×4 NumPy array by 90 degrees counterclockwise.
#🔹 Flatten a 3D NumPy array into a 1D array.
import numpy as np
###🔹 Generate a 5×5 matrix where elements on the border are 1, and the inside is 0.
array = np.ones((5,5))
array [1:-1,1:-1]=0
print(array)


###🔹 Reshape a 1D array of 20 elements into a 4×5 matrix without using reshape().
arr = np.arange(20)  # Creating a 1D array with 20 elements
rows, cols = 4, 5
matrix = [arr[i * cols:(i + 1) * cols] for i in range(rows)]
print(np.array(matrix))

###🔹 Rotate a given 4×4 NumPy array by 90 degrees counterclockwise.
array = np.arange(16).reshape(4, 4)  # Sample 4×4 array
rotated = np.rot90(array)  # Rotate 90° counterclockwise
print(rotated)

###🔹 Flatten a 3D NumPy array into a 1D array.
array_3d = np.random.randint(0, 10, (2, 3, 4))  # Example 3D array (2×3×4)
flattened = array_3d.flatten()  # Convert to 1D
print(flattened)


[1 5 8 1 1 7 4 8 8 3 9 3 0 5 6 6 1 7 5 0 1 5 4 1]


In [103]:
import numpy as np
arr = np.ones((4,4))
print(arr)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


#2. Mathematical Operations
#🔹 Create a 5×5 random matrix and normalize it (scale values between 0 and 1).
import numpy as np
matrix = np.random.rand(5,5)
normalized_matrix = (matrix - matrix.min()) / (matrix.max() - matrix.min())
print(matrix)
print(normalized_matrix)

#🔹 Find the row-wise and column-wise sum of a given matrix.
matrix = np.random.randint(1,10,(3,3))
row_sum = matrix.sum(axis=1)
col_sum = matrix.sum(axis=0)
print(matrix)
print(row_sum)
print(col_sum)

#🔹 Compute the dot product and cross product of two 3D vectors.
vector1 = np.array([1,2,3])
vector2 = np.array([4,5,6])
dot_product = np.dot(vector1,vector2)
cross_product = np.cross(vector1,vector2)
print(dot_product)
print(cross_product)

#🔹 Create a function that computes the Euclidean distance between two NumPy arrays.
def euclidean_distance(a, b):
   return np.sqrt(np.sum((a - b) ** 2))
Example arrays
A = np.array([1, 2, 3])
B = np.array([4, 5, 6])
Compute Euclidean distance
distance = euclidean_distance(A, B)
print("Euclidean Distance:", distance)
